# Generated by Django 4.2.1 on 2023-06-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
